name: PR Setting

on:
  pull_request: # or pull_request_target
    types:
      - opened
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # 위에 작성한 설정 파일을 읽기 위해 필요
      pull-requests: write # PR에 라벨을 추가하기 위해 필요
    steps:
      - name: Run PR Labeler And Assignee
        uses: kek2410/pr-labeler@v1.0.0
        with:
          configuration-path: .github/labeler-config.yml
          assignees: author
